name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
      - name: Build with Gradle
        run: make build
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CODECLIMATE_KEY}}
          JACOCO_SOURCE_PATH: "src/main/java"
        with:
          coverageLocations: build/reports/jacoco/test/jacocoTestReport.xml:jacoco